name: file_logging
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ">=2.18.6 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  logging: ^1.1.0
  meta: ^1.8.0
