name: file_logging
description: simple extension on `logging` package to handle logging into files using isolates (this is not supported in web)
version: 1.0.0
repository: https://github.com/FMotalleb/file_logging

environment:
  sdk: ">=2.18.6 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  logging: ^1.1.0
  meta: ^1.8.0
